# Generated by Django 2.1.5 on 2019-01-16 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(blank=True)),
                ('gender', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], default='male', max_length=10)),
                ('city', models.CharField(blank=True, choices=[('kyiv', 'Киев'), ('harkov', 'Харьков'), ('lvov', 'Львов'), ('dnepr', 'Днепропетровск'), ('osessa', 'Одесса'), ('herson', 'Херсон'), ('vyshgorod', 'Вышгород'), ('kovel', 'Ковель')], max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
