# Generated by Django 2.1.5 on 2019-01-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('kyiv', 'Киев'), ('harkov', 'Харьков'), ('lvov', 'Львов'), ('dnepr', 'Днепропетровск'), ('osessa', 'Одесса'), ('herson', 'Херсон'), ('vyshgorod', 'Вышгород'), ('kovel', 'Ковель')], default='kyiv', max_length=30),
        ),
    ]
